[
  {
    title: "Dispatcher in OS",
    subtitle: "Importance, functions and working",
    date: "05 September 2024",
    slug: "18.dispatcher-in-os",
  },
  {
    title: "Schedulers in OS",
    subtitle: "LTS, STS and MTS",
    date: "04 September 2024",
    slug: "17.schedulers-in-os",
  },
  {
    title: "Process queues in OS",
    subtitle: "Job, Ready & Device queue",
    date: "03 September 2024",
    slug: "16.process-queues",
  },
  {
    title: "Process lifecycle",
    subtitle: "Process Control Block & lifecycle",
    date: "02 September 2024",
    slug: "15.process-lifecycle",
  },
  {
    title: "Program to process",
    subtitle: "Step by step process",
    date: "01 September 2024",
    slug: "14.program-to-process",
  },
  {
    title: "Storage in Computer System",
    subtitle: "Types and examples",
    date: "31 August 2024",
    slug: "13.storage-in-computers",
  },
  {
    title: "Overview of Booting process",
    subtitle: "Process and types",
    date: "30 August 2024",
    slug: "12.overview-of-booting",
  },
  {
    title: "What is a System Call?",
    subtitle: "Interface and types of SC",
    date: "29 August 2024",
    slug: "11.system-calls",
  },
  {
    title: "Inter Process Communication",
    subtitle: "Key features and mechanisms",
    date: "28 August 2024",
    slug: "10.inter-process-communication",
  },
  {
    title: "Functions of Kernel",
    subtitle: "Key functions and type of kernel",
    date: "27 August 2024",
    slug: "09.functions-and-types-of-kernel",
  },
  {
    title: "Modes of Operating System",
    subtitle: "Types of modes and their switching",
    date: "27 August 2024",
    slug: "08.modes-of-operating-system",
  },
  {
    title: "Multi-tasking & Multi-threading",
    subtitle: "Definitions along with pros and cons",
    date: "26 August 2024",
    slug: "07.multi-tasking-and-multi-threading",
  },
  {
    title: "Program, process and thread",
    subtitle: "Definition and the differences",
    date: "25 August 2024",
    slug: "06.program-process-thread",
  },
  {
    title: "Operating Systems",
    subtitle: "Overview of OS",
    date: "15 August 2024",
    slug: "05.operating-systems",
  },
  {
    title: "Open Systems Interconnection",
    subtitle: "Overview of OSI model",
    date: "14 August 2024",
    slug: "04.open-systems-interconnection",
  },
  {
    title: "Execution in Computers",
    subtitle: "Process of application executions",
    date: "13 August 2024",
    slug: "03.how-applications-execute",
  },
  {
    title: "Software and Hardware",
    subtitle: "Components of Computer systems",
    date: "12 August 2024",
    slug: "02.hardware-and-software",
  },
  {
    title: "Bits, bytes and binary",
    subtitle: "How data is stored in Computer systems",
    date: "11 August 2024",
    slug: "01.bits-bytes-binary",
  },
]
